/* eslint-disable camelcase  -- 'Poodle__factory' is auto generated*/
import { ethers } from 'ethers';
import { Stake__factory } from 'smart-contract';
import type { JsonRpcSigner } from 'ethers';

export default async function stakeNft(
	signer: JsonRpcSigner | undefined
): Promise<void> {
	if (typeof window.ethereum !== 'undefined') {
		const poodle = new ethers.Contract(
			'0x9fe46736679d2d9a65f0992f2272de9f3c7fa6e0',
			// eslint-disable-next-line camelcase, @typescript-eslint/no-unsafe-argument -- Autogenerated name
			Stake__factory.abi,
			signer
		);
		try {
			const tx = await poodle.stakeNFT(1);
			await tx.wait();
			console.log('Successfully minted');
		} catch (e) {
			console.log(e);
		}
	}
}
